# Copyright (c) 2016-2018 Clearmatics Technologies Ltd
# SPDX-License-Identifier: LGPL-3.0+

FROM ubuntu:17.10

# Information about the docker image
LABEL version="1.0"
LABEL maintainer="opensource@clearmatics.com"

# Skip apt's interactive post install configuration steps
ENV DEBIAN_FRONTEND=noninteractive

# Install geth
RUN apt-get update && apt-get install --yes software-properties-common
RUN add-apt-repository ppa:ethereum/ethereum
RUN apt-get update && apt-get install --yes geth

# Install bash
RUN apt-get update && apt-get install bash

# Add a user
RUN adduser --disabled-login --gecos "" eth_user
COPY eth_common /home/eth_user/eth_common
RUN chown -R eth_user:eth_user /home/eth_user/eth_common
USER eth_user

# Set up the working directory
WORKDIR /home/eth_user

# Build arguments whose values are given to env variables to configure the docker images from one node to another
ARG identity_arg
ARG rpcport_arg
ENV identity_env $identity_arg
ENV rpcport_env $rpcport_arg

# Make the startNode script executable by the eth_user
COPY startNode.sh /home/eth_user

# Start a bash session (the user has to run ./startNode.sh from the WORKDIR when he wants to start the node)
ENTRYPOINT /bin/bash
